name: actions-zola
description: build static sites with zola
author: wass3r
branding:
  icon: book
  color: blue
inputs:
  zola_version:
    description: zola version
    default: v0.11.0
runs:
  using: docker
  image: Dockerfile
